name: ci

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [13, 14, 15, 16, 17]
    steps:
       - name: Docker meta
         id: meta
         uses: docker/metadata-action@v5
       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
         with:
           driver: docker-container
       - name: Build and push
         id: docker_build
         uses: docker/build-push-action@v6
         with:
           push: true
           platforms: linux/amd64,linux/arm64
           build-args: |
             POSTGRES_VERSION=${{ matrix.version }}
           tags: siemens/postgres-backup-s3:${{ matrix.version }}
           labels: ${{ steps.meta.outputs.labels }}
